/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BlocNotas;

/**
 *
 * @author Lenovo LOQ
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuNuevaPestaña = new javax.swing.JMenuItem();
        jMenuIAbrirArchivo = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuCambiarTamaño = new javax.swing.JMenuItem();
        jMenuCambiarColor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu4.setText("Archivo");

        jMenuNuevaPestaña.setText("Nueva Pestaña");
        jMenuNuevaPestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevaPestañaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuNuevaPestaña);

        jMenuIAbrirArchivo.setText("Abrir Archivo");
        jMenuIAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIAbrirArchivoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuIAbrirArchivo);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuGuardar);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Editar");

        jMenuCambiarTamaño.setText("Cambiar tamaño de letra");
        jMenuCambiarTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCambiarTamañoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCambiarTamaño);

        jMenuCambiarColor.setText("Cambiar color");
        jMenuCambiarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCambiarColorActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCambiarColor);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCambiarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCambiarColorActionPerformed
        // TODO add your handling code here:
        Controller.cambiarColor(jTextArea1, this);
    }//GEN-LAST:event_jMenuCambiarColorActionPerformed

    private void jMenuCambiarTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCambiarTamañoActionPerformed
        // TODO add your handling code here:
        Controller.cambiarTamanoLetra(jTextArea1, this);
    }//GEN-LAST:event_jMenuCambiarTamañoActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
        Controller.guardarArchivo(jTextArea1, this);
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuIAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIAbrirArchivoActionPerformed
        // TODO add your handling code here:
        Controller.abrirArchivo(jTextArea1, this);
    }//GEN-LAST:event_jMenuIAbrirArchivoActionPerformed

    private void jMenuNuevaPestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevaPestañaActionPerformed
        // TODO add your handling code here:
        Controller.nuevaPestaña();
    }//GEN-LAST:event_jMenuNuevaPestañaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCambiarColor;
    private javax.swing.JMenuItem jMenuCambiarTamaño;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuIAbrirArchivo;
    private javax.swing.JMenuItem jMenuNuevaPestaña;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
