/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ComponentesGrupo2;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo LOQ
 */
public class InterfazGrupo2 extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrupo2
     */
    DefaultComboBoxModel modelo;
    private int valorLaptop;
    private int valorAlmacenamiento;
    private int mesesDiferidos;

    public int getMesesDiferidos() {
        return mesesDiferidos;
    }

    public void setMesesDiferidos(int mesesDiferidos) {
        this.mesesDiferidos = mesesDiferidos;
    }

    public int getValorAlmacenamiento() {
        return valorAlmacenamiento;
    }

    public void setValorAlmacenamiento(int valorAlmacenamiento) {
        this.valorAlmacenamiento = valorAlmacenamiento;
    }

    public int getValorLaptop() {
        return valorLaptop;
    }

    public void setValorLaptop(int valorLaptop) {
        this.valorLaptop = valorLaptop;
    }

    public InterfazGrupo2() {
        initComponents();
        cargaComboBox();
        activarDiferir();

    }

//Estudiar en la casa
    public void cargaComboBox() {
        String[] modelos = {"ASUS", "DELL", "MSI"};
        modelo = new DefaultComboBoxModel(modelos);
        jcbxModelos.setModel(modelo);
    }

    public void activarDiferir() {
        // TODO add your handling code here:
        if (jtglBtnDiferir.isSelected()) {
            jscrMeses.setEnabled(true);
            jtglBtnDiferir.setBackground(Color.GREEN);
            setMesesDiferidos(jscrMeses.getValue());
        } else {
            jscrMeses.setEnabled(false);
            jtglBtnDiferir.setBackground(Color.red);
            setMesesDiferidos(0);
        }
    }

    public void estadoRegalos() {
        if (jcbxModelos.getSelectedItem().equals("MSI")) {
            jchkAudifonos.setSelected(false);
            jchkMouse.setSelected(false);
            jchkUsb.setSelected(false);
            jchkAudifonos.setEnabled(false);
            jchkMouse.setEnabled(false);
            jchkUsb.setEnabled(false);
        } else {
            jchkAudifonos.setEnabled(true);
            jchkMouse.setEnabled(true);
            jchkUsb.setEnabled(true);
        }
    }
    
    public String regalosElegidos (){
        String regalos = "";
        if (jchkMouse.isSelected()) {
        regalos += "Mouse "; 
        }
        if (jchkAudifonos.isSelected()) {
        regalos += "Audifonos ";
        }
        if (jchkUsb.isSelected()) {
        regalos += "USB ";
        }
        return regalos;  
    }
    
    

    /*
    public void calcularLaptop() {
        if (jcbxModelos.getSelectedItem().equals("Lenovo")) {
            setValorLaptop(1200);
        } else if (jcbxModelos.getSelectedItem().equals("Lenovo")) {
            setValorLaptop(600);
        } else if (jcbxModelos.getSelectedItem().equals("MSI")) {
            setValorLaptop(800);
        }
    }
*/
    
    public void calcularLaptop(){ setValorLaptop(jcbxModelos.getSelectedItem().equals("ASUS") ? 1200 : jcbxModelos.getSelectedItem().equals("DELL") ? 600 : jcbxModelos.getSelectedItem().equals("MSI") ? 800 : 0); }
    
    public void calcularAlmacenamiento () {setValorAlmacenamiento(jrbtn256GB.isSelected() ? 20 : jrbtn512GB.isSelected() ? 40 : jrbtn1TB.isSelected() ? 60 : jrbtn2TB.isSelected() ? 120 : 0);}

    public void facturacion() {
        calcularLaptop();
        calcularAlmacenamiento();
        String regalosRecogidos = regalosElegidos();
        JOptionPane.showMessageDialog(this, "El valor por la laptop Seleccionada es: " + getValorLaptop() + "\n" + "El valor por el almacenamiento seleccionado es: \n" + getValorAlmacenamiento() + "\n" + "Los regalos elegidos son: " + regalosRecogidos + "\n" + "Los mese a diferir son: " + getMesesDiferidos());
    }
    /*
    public void cargaComboBox() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcbxModelos.getModel();
        String[] modelos = {"ASUS", "DELL", "MSI"};
        for (String m : modelos) {
            modelo.addElement(m);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRadioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbtn256GB = new javax.swing.JRadioButton();
        jrbtn512GB = new javax.swing.JRadioButton();
        jrbtn1TB = new javax.swing.JRadioButton();
        jrbtn2TB = new javax.swing.JRadioButton();
        jcbxModelos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jchkMouse = new javax.swing.JCheckBox();
        jchkAudifonos = new javax.swing.JCheckBox();
        jchkUsb = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtglBtnDiferir = new javax.swing.JToggleButton();
        jscrMeses = new javax.swing.JScrollBar();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRadioGroup.add(jrbtn256GB);
        jrbtn256GB.setText("256 GB");
        jrbtn256GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn256GBActionPerformed(evt);
            }
        });

        btnRadioGroup.add(jrbtn512GB);
        jrbtn512GB.setText("512 GB");
        jrbtn512GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn512GBActionPerformed(evt);
            }
        });

        btnRadioGroup.add(jrbtn1TB);
        jrbtn1TB.setText("1 TB");
        jrbtn1TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn1TBActionPerformed(evt);
            }
        });

        btnRadioGroup.add(jrbtn2TB);
        jrbtn2TB.setText("2 TB");

        jcbxModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lenovo", "Asus", "Dell", "MSI", " " }));
        jcbxModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxModelosActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccion de Modelo");

        jchkMouse.setText("Mouse");
        jchkMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMouseActionPerformed(evt);
            }
        });

        jchkAudifonos.setText("Audifonos");
        jchkAudifonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAudifonosActionPerformed(evt);
            }
        });

        jchkUsb.setText("USB");

        jLabel2.setText("Seleccion de Almacenamiento");

        jLabel3.setText("Regalos Disponibles");

        jtglBtnDiferir.setText("Diferir");
        jtglBtnDiferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtglBtnDiferirActionPerformed(evt);
            }
        });

        jscrMeses.setBackground(new java.awt.Color(153, 153, 255));
        jscrMeses.setBlockIncrement(3);
        jscrMeses.setForeground(new java.awt.Color(153, 153, 255));
        jscrMeses.setMaximum(13);
        jscrMeses.setMinimum(3);
        jscrMeses.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jscrMeses.setUnitIncrement(3);
        jscrMeses.setVisibleAmount(3);
        jscrMeses.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jscrMesesAdjustmentValueChanged(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbtnComprar.setText("Comprar");
        jbtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnComprar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtglBtnDiferir)
                        .addGap(18, 18, 18)
                        .addComponent(jscrMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbtn2TB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbtn1TB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbtn512GB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbtn256GB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jchkMouse)
                            .addComponent(jchkAudifonos)
                            .addComponent(jchkUsb)
                            .addComponent(jLabel1))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jrbtn256GB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtn512GB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtn1TB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtn2TB))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbxModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkMouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkAudifonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkUsb)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtglBtnDiferir)
                    .addComponent(jscrMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnComprar)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn256GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn256GBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn256GBActionPerformed

    private void jrbtn1TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn1TBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn1TBActionPerformed

    private void jrbtn512GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn512GBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn512GBActionPerformed

    private void jchkAudifonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAudifonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkAudifonosActionPerformed

    private void jtglBtnDiferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtglBtnDiferirActionPerformed
        activarDiferir();
    }//GEN-LAST:event_jtglBtnDiferirActionPerformed

    private void jchkMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkMouseActionPerformed

    private void jcbxModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxModelosActionPerformed
        // TODO add your handling code here:
        estadoRegalos();
    }//GEN-LAST:event_jcbxModelosActionPerformed

    private void jscrMesesAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jscrMesesAdjustmentValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jscrMesesAdjustmentValueChanged

    private void jbtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComprarActionPerformed
        // TODO add your handling code here:
        facturacion();
    }//GEN-LAST:event_jbtnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrupo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnRadioGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnComprar;
    private javax.swing.JComboBox<String> jcbxModelos;
    private javax.swing.JCheckBox jchkAudifonos;
    private javax.swing.JCheckBox jchkMouse;
    private javax.swing.JCheckBox jchkUsb;
    private javax.swing.JRadioButton jrbtn1TB;
    private javax.swing.JRadioButton jrbtn256GB;
    private javax.swing.JRadioButton jrbtn2TB;
    private javax.swing.JRadioButton jrbtn512GB;
    private javax.swing.JScrollBar jscrMeses;
    private javax.swing.JToggleButton jtglBtnDiferir;
    // End of variables declaration//GEN-END:variables
}
