/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ComponentesGrupo1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo LOQ
 */
public class InterfazPractica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPractica
     */
    DefaultListModel lista = new DefaultListModel();
    DefaultTableModel tabla;
    int resultadoSuma;

    public int getResultadoSuma() {
        return resultadoSuma;
    }

    public void setResultadoSuma(int resultado) {
        this.resultadoSuma = resultado;
    }

    public InterfazPractica() {
        initComponents();
        cargarLista();
        cargarColumnas();
    }

    public void cargarLista() {
        String[] valoresLista = {"Suma", "Resta", "Multiplicacion", "Division"};

        for (String valor : valoresLista) {
            lista.addElement(valor);
        }
        jlistPrincipal.setModel(lista);
    }

    public void cargarColumnas() {
        String[] columnas = {"Numero 1", "Numero 2", "Resultado", "Operacion"};
        tabla = new DefaultTableModel(null, columnas);
        jtblPrincipal.setModel(tabla);

    }
    public void cargarFilas() {
    String [] filas = new String [4];
    filas [0] = jtxtFNumero1.getText();
    filas [1] = jtxtFNumero2.getText();
    filas [2] = jtxtFResultado.getText();
    filas [3] = jlistPrincipal.getSelectedValue();
    tabla.addRow(filas);
    }

    public void suma(int numero1, int numero2) throws MiException {
        setResultadoSuma(numero1 + numero2);
        jtxtFResultado.setText(String.valueOf(getResultadoSuma()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtFNumero1 = new javax.swing.JTextField();
        jtxtFNumero2 = new javax.swing.JTextField();
        jtxtFResultado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistPrincipal = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblPrincipal = new javax.swing.JTable();
        jtxtFIndice = new javax.swing.JTextField();
        jbtnIndice = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtFNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFNumero1ActionPerformed(evt);
            }
        });

        jtxtFResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFResultadoActionPerformed(evt);
            }
        });

        jlistPrincipal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistPrincipal);

        jtblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblPrincipal);

        jbtnIndice.setText("Buscar Indice");

        jbtnSuma.setText("Sumar");
        jbtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtFNumero1)
                        .addComponent(jtxtFNumero2)
                        .addComponent(jtxtFResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtFIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIndice))
                    .addComponent(jbtnSuma))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtFNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtFIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnIndice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSuma)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFNumero1ActionPerformed

    private void jtxtFResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFResultadoActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        // TODO add your handling code here:
        String texto1 = jtxtFNumero1.getText();
        String texto2 = jtxtFNumero2.getText();
        if (texto1.isEmpty() || texto2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo vacio");
            return;
        }
        try {
            int numero1 = Integer.valueOf(texto1);
            int numero2 = Integer.valueOf(texto2);
            suma(numero1, numero2);
            cargarFilas();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Solo numeros");
        } catch (MiException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jbtnSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPractica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnIndice;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JList<String> jlistPrincipal;
    private javax.swing.JTable jtblPrincipal;
    private javax.swing.JTextField jtxtFIndice;
    private javax.swing.JTextField jtxtFNumero1;
    private javax.swing.JTextField jtxtFNumero2;
    private javax.swing.JTextField jtxtFResultado;
    // End of variables declaration//GEN-END:variables
}
